booking/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    #form page
    path('prendre-rendez-vous/', views.booking, name='prendre-rendez-vous'),
    #populate fields request
    path('get-interventions/<int:service>/', views.getInterventions.as_view(), name='interventions'),
    path('get-doctors/<int:service>/', views.getDoctors.as_view(), name='doctors'),
    #check request
    path('create-appointment/<int:service>/<int:intervention>/<int:doctor>/<str:dateStart>/<str:dateStop>/', views.createAppointment.as_view(), name='create_appointment'),
    #register request
    path('register-appointment/<int:intervention>/<int:doctor>/<str:dateStart>/<str:dateStop>/', views.registerAppointment.as_view(), name='register_appointment'),
    ]

soignemoi/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls')),
    path('securelogin/', admin.site.urls),
    path('',views.home, name='home'),
    path('', include('homepage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usermanager/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('nouveau_patient/', views.register, name='nouveau_patient'),
    path('connection/', views.login, name='connection'),
    path('nouveau_visiteur/', views.register_visitor, name='nouveau_visiteur'),
    path('mon_espace_visiteur/', views.visitordashboard, name='mon_espace_visiteur'),
    path('mon_profil/', views.profile, name='mon_profil'),
    path('deconnection/', views.logout, name='logout'),
]

usermanager/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.signals import post_save


# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, password=None):


        if not username:
            raise ValueError('User must have an username')

        user = self.model(
            username = self.normalize_email(username),
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, password):
            user = self.create_user(
                username = self.normalize_email(username),

                password = password,
                first_name = first_name,
                last_name = last_name,
            )
            user.is_admin = True
            user.is_staff = True
            user.is_active = True
            user.save(using=self._db)
            return user

class Account(AbstractBaseUser):
    first_name      =models.CharField(max_length=50)
    last_name       =models.CharField(max_length=50)
    username        =models.CharField(max_length=150, unique=True)

    #required
    date_joined     =models.DateTimeField(auto_now_add=True)
    last_login      =models.DateTimeField(auto_now_add=True)
    is_admin        =models.BooleanField(default=False)
    is_staff        =models.BooleanField(default=False)
    is_active       =models.BooleanField(default=False)

   
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS =[ 'first_name','last_name']

    objects = MyAccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True
    




class DoctorProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE, blank=True, null=True)
    service = models.CharField(max_length=30, blank=True)#, choices=SERVICE_CHOICES)
    speciality = models.CharField(max_length=30, blank=True)

    class Meta:
        verbose_name = 'doctor profile'
        verbose_name_plural = 'doctor profiles'

    def __str__(self):
        return self.user.username
    
    def full_name(self):
        return self.user.first_name.upper() + " " + self.user.last_name
    

class PatientProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE, blank=True, null=True)
    address_line_1 = models.CharField(blank=True, max_length=100)
    address_line_2 = models.CharField(blank=True, max_length=100)
    city = models.CharField(blank=True, max_length=20)
    zipcode = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    class Meta:
        verbose_name = 'visitor profile'
        verbose_name_plural = 'visitor profiles'

    def __str__(self):
        return self.user.username

    def full_name(self):
        return self.user.first_name.upper() + " " + self.user.last_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}' 



class SecretaryProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'secretary profile'
        verbose_name_plural = 'secretary profiles'

    def __str__(self):
        return self.user.username
    
    def full_name(self):
        return self.user.first_name.upper() + " " + self.user.last_name


class PlanningManagerProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'planning manager profile'
        verbose_name_plural = 'planning manager profiles'

    def __str__(self):
        return self.user.username
    
    def full_name(self):
        return self.user.first_name.upper() + " " + self.user.last_name

usermanager/forms/registerationforms.py
from django import forms
from ..models import Account, PatientProfile

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Mot de passe',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirmer le mot de passe',
        'class': 'form-control',
    }))

    username = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Adresse email',
        'class': 'form-control',
    }))

    class Meta:
        model = Account
        fields = ( 'username', 'first_name', 'last_name','password')

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        username = cleaned_data.get('email')
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if Account.objects.filter(username=username).exists():
            raise forms.ValidationError(
                "L'adresse email existe déjà"
            )

        if password != confirm_password:
            raise forms.ValidationError(
                "Les mots de passe ne correspondent pas"
            )
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Adresse email'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Nom d\'utilisateur'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Prénom d\'utilisateur'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class PatientProfileForm(forms.ModelForm):
    class Meta:
        model  = PatientProfile
        fields = ('address_line_1', 'address_line_2', 'city', 'zipcode', 'country')

    def __init__(self, *args, **kwargs):
        super(PatientProfileForm, self).__init__(*args, **kwargs)
        self.fields['address_line_1'].widget.attrs['placeholder'] = 'Adresse ligne 1'
        self.fields['address_line_2'].widget.attrs['placeholder'] = 'Adresse ligne 2'
        self.fields['city'].widget.attrs['placeholder'] = 'Ville'
        self.fields['zipcode'].widget.attrs['placeholder'] = 'Code postal'
        self.fields['country'].widget.attrs['placeholder'] = 'Pays'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

usermanager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms.registerationforms import RegistrationForm, PatientProfileForm
from .models import Account, PatientProfile
from django.contrib import messages, auth
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

# Create your views here.
def register (request):
    if request.method == 'POST':
       form = RegistrationForm(request.POST)
       if form.is_valid():
           username = form.cleaned_data['username']
           first_name = form.cleaned_data['first_name']
           last_name = form.cleaned_data['last_name']
           password = form.cleaned_data['password']
           user = Account.objects.create_user(username=username, first_name=first_name, last_name=last_name, password=password)
           user.is_active = True
           print(user)
           user.save()
           PatientProfile.objects.create(user=user)
           messages.success(request, 'Votre compte a été créé avec succès')
           return redirect('connection')
       else:
            for filed, errors in form.errors.items():
                for error in errors:
                    messages.error(request, error, extra_tags='danger')
            return render(request, 'usermanager/register.html', {'form': form})
    else:
        form = RegistrationForm()
    return render(request, 'usermanager/register.html', {'form': form})

def login (request):
    if request.method == 'POST':
        username = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        
        if user is not None:
            if user.is_active:
                auth.login(request, user)
                # case : User is a patient and has a completed profile
                if hasattr(user, 'patientprofile'):  # Check if the user has a PatientProfile
                    if user.patientprofile.address_line_1 != '':  # Check if address_line_1 is empty
                        return redirect('mon_espace_visiteur')
                    # case : User is visitor but has no profile
                    else:
                        return redirect('nouveau_visiteur')
                else:
                    messages.error(request, 'Votre compte n\'a pas de profile visiteur. Veuillez contacter l\'administrateur', extra_tags='danger')
                    auth.logout(request)
                    return redirect('connection')
        else:
            messages.error(request, 'Problème d\'authentification', extra_tags='danger')
    else:
        messages.error(request, 'Problème de méthode', extra_tags='danger')
    return render(request, 'usermanager/login.html')

@login_required
def register_visitor(request):
    visitorprofile = get_object_or_404(PatientProfile, user=request.user)
    visitorform = PatientProfileForm(request.POST or None, instance=visitorprofile)
    if request.method == 'POST':
        if visitorform.is_valid():
            address_line_1 = visitorform.cleaned_data['address_line_1']
            address_line_2 = visitorform.cleaned_data['address_line_2']
            city = visitorform.cleaned_data['city']
            zipcode = visitorform.cleaned_data['zipcode']
            country = visitorform.cleaned_data['country']
            visitorprofile.save()
            messages.success(request, 'Votre profile a été mis à jour')
            return redirect('mon_espace_visiteur')
        else:
            for error in visitorform.errors.values():
                for error_message in error:
                    messages.error(request, error_message, extra_tags='danger')
            return render(request, 'usermanager/nouveau_visiteur.html', {'visitorform': visitorform})
    return render(request, 'usermanager/nouveau_visiteur.html')

@login_required
def visitordashboard (request):
    visitorprofile = get_object_or_404(PatientProfile, user=request.user)
    if visitorprofile.address_line_1 != '':
        pass
    else:
        messages.info(request, 'Veuillez compléter votre profile')
        return redirect('nouveau_visiteur')
    context = {
        'visitorprofile': visitorprofile
    }
    return render(request, 'usermanager/mon_espace_visiteur.html', context)

@login_required
def profile(request):
    patient_profile = get_object_or_404(PatientProfile, user=request.user)
    context = {
        'patient_profile': patient_profile,
    }
    return render(request, 'usermanager/mon_profil.html', context)

@login_required
def logout (request):
    auth.logout(request)
    messages.success(request, 'Vous êtes déconnecté')
    return redirect('connection')

usermanager/templates/usermanager/login.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static '/elements/logo/soignemoi-favicon-color.ico' %}">

  </head>
  <body>



    <!-- start of login form -->

    <section class="section-content padding-y">
      {% include 'includes/alerts.html' %}

      <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body text-center">
              <header class="mb-2"><h3 class="card-title">Vous avez déjà un compte SoigneMoi?</h3></header>
              <p class="pt-4 mb-4 pb-2">
                  Pour vous connecter à votre espace utilisateur, entrez le mail et le mot de passe associés à votre compte SoigneMoi.
                </p>
          <form action="{% url 'connection' %}" method="POST" class="form-control form-control-lg py-2 gap-4 text-start">
        {% csrf_token %}

        <div class="fomr-group">
          <label class="mt-1 mb-1">Email</label>
            <input type="email" class="form-control" placeholder="Email Address" name="email" required>
          <label class="mt-1 mb-1">Mot de passe</label>
            <input type="password" class="form-control" placeholder="Password" name="password" required>
          <div class="form-group mt-4">
            <button type="submit" class="btn btn-warning btn-lg btn-block w-100">Se connecter</button>
          </div>
        </div>
          </form>
              </div>
              </div>

          </article>
              
          <div class="text-center py-2">
            Vous n'avez pas encore de compte ? <a href="{% url 'nouveau_patient' %}">Créez-en un</a>
          </div>
    </section> 

  </body>
</html>

usermanager/templates/usermanager/mon_espace_visiteur.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static '/elements/logo/soignemoi-favicon-color.ico' %}">

  </head>
  <body>

    <section class="section-conten padding-y bg">

      {% include 'includes/alerts.html' %}
      <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}
        <main class="col-md-9">
          <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Connecté en tant que:</strong>
            <span>{{user.full_name}}</span>
          </header>
          <div class="card-body">
            <div class="row">
      
            <div class="col-md-6">
              <div class="card" style="text-align:center;">
                <div class="card-body">
                  <h5 class="card-title">Mes rendez-vous : </h5>

                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card" style="text-align:center;">
                <div class="card-body">

                </div>
              </div>
            </div>
      
            </div> <!-- row.// -->
          </div> <!-- card-body .// -->
      
          </article> <!-- order-group.// -->
        </main>
      </div> <!-- row.// -->
      </div>
      
      
      </section>

usermanager/templates/usermanager/mon_profil.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title></title>
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <link rel="icon" type="image/x-icon" href="{% static '/elements/logo/soignemoi-favicon-color.ico' %}">

</head>

<body>

  <section class="section-conten padding-y bg">

    {% include 'includes/alerts.html' %}
    <div class="container">
      <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}


        <main class="col-md-9">
          <article class="card">
            <header class="card-header">
              <strong class="d-inline-block mr-3">Mes informations</strong>
            </header>
            <div class="card-body">
              <div class="row">
                <h5 class="card-title">Mon compte : </h5>
                      <div class="text-start">
                        <p>Email: {{ patient_profile.user.username }}</p>
                        <p>Nom: {{ patient_profile.user.last_name }}</p>
                        <p>Prénom: {{ patient_profile.user.first_name }}</p>
                        <p>Address: {{ patient_profile.full_address }}</p>
                  <hr>
                  <h5 class="card-title">Renseignements : </h5>
                        <div>
                          <p>Addresse: {{ patient_profile.address_line_1 }}</p>
                          <p>Complément d'addresse : {{ patient_profile.addresse_line_2 }}</p>

                          <p>Ville: {{ patient_profile.city }}</p>
                          <p>Code postal: {{ patient_profile.zip_code }}</p>
                          <p>Pays: {{ patient_profile.country }}</p>
                        </div>
              </div> <!-- card-body .// -->

          </article> <!-- order-group.// -->
        </main>
      </div> <!-- row.// -->
    </div>


  </section>

usermanager/templates/usermanager/nouveau_visiteur.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static '/elements/logo/soignemoi-favicon-color.ico' %}">

  </head>

<body>



    <a class="btn btn-light btn-block" href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Déconnection</span> </a>

  </section>

  <section class="section-content padding-y">

    <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body text-center">
        <header class="mb-2">
          <h3 class="card-title">Complétez vos informations :</h3>
        </header>
        <p class="pt-4 mb-4 pb-2">
          <p>
           Bonjour {{ user.full_name }},
         </p>
        </p>
          pour continuer, veuillez remplir les informations suivantes :
        </p>
        {% include 'includes/alerts.html' %}

        <form action="{% url 'nouveau_visiteur' %}" method="POST">
          {% csrf_token %}


          <div class="form-group">

                <label for="id_address_line_1">Adresse</label>
                <input type="text" name="address_line_1" class="form-control" id="id_address_line_1">
                <label for="id_address_line_2">Complément d'addresse:</label>
                <input type="text" name="address_line_2" class="form-control" id="id_address_line_2">
                <label for="city">Ville:</label>
                <input type="text" name="city" class="form-control" id="city">
                <label for="zip_code">Code postal:</label>
                <input type="text" name="zip_code" class="form-control" id="zip_code">
                <label for="country">Pays</label>
                <input type="text" name="country" class="form-control" id="country">

              <div class="form-group mt-4">
                <button type="submit" class="btn btn-warning btn-lg btn-block w-100"> Validez votre profile </button>
              </div>
          </div>
        </form>
    </div>
    </div>

    </article>

</body>
</html>

usermanager/templates/usermanager/patient_info.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static '/elements/logo/soignemoi-favicon-color.ico' %}">

  </head>


<body>
  <section class="section-content padding-y">
  {% include 'includes/alerts.html' %}
    <p> Mes infos sont déja renseignées</p>

    <a class="btn btn-light btn-block" href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Déconnection</span> </a>
  </section>

</body>
</html>

usermanager/templates/usermanager/register.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hopital SoigneMoi</title>

  <!-- custom javascript -->
  <script src="{% static '/js/jquery.min.js' %}"></script>
  <script src="{% static '/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>

  <!-- custom css -->
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">


  <link rel="icon" type="image/x-icon" href="{% static '/elements/logo/soignemoi-favicon-color.ico' %}">
</head>

<body>
  <script src="{% static 'js/script.js' %}"></script>


  {% block content %}


  <!-- start of register form -->
  {% load i18n %}


  <section class="section-content padding-y">

    <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body text-center">
        <header class="mb-2">
          <h3 class="card-title">Créer votre compte SoigneMoi</h3>
        </header>
        <p class="pt-4 mb-4 pb-2">
          Pour créer votre compte SoigneMoi, veuillez renseigner les
          champs ci-dessous.
        </p>
        {% include 'includes/alerts.html' %}

        <form action="{% url 'nouveau_patient' %}" method="POST"
          class="form-control form-control-lg py-2 gap-4 text-start">
          {% csrf_token %}



          <div class="form-group">


            <div style="display: flex; justify-content: space-between;">
              <div>
                <label for="id_first_name">Nom</label>
                {{ form.first_name }}
              </div>
              <div>
                <label for="id_last_name">Prénom</label>
                {{ form.last_name }}
              </div>
            </div>
            <label class="mt-1 mb-1">Email</label>
            {{ form.username }}
                       <labe class="mt-1 mb-1" l>Mot de passe</label>
              {{ form.password }}
              <label class="mt-1 mb-1">Confirmer le mot de passe</label>
              {{ form.confirm_password }}
              <div class="form-group mt-4">
                <button type="submit" class="btn btn-warning btn-lg btn-block w-100"> Créer votre profile </button>
              </div>
          </div>
        </form>
    </div>
    </div>

    </article>

    <div class="text-center py-2">
      Vous avez déjà un compte ? <a href="{% url 'connection' %}">Connectez-vous</a>
    </div>


    </div>

  </section>

  <!-- end of register form -->

</body>

</html>
{% endblock content %}